export const TEAM_NAME_TO_TWITTER_PAGE = {
  Juventus: 'juventusfcen',
  Inter: 'Inter_en',
  'AC Milan': 'acmilan',
  Napoli: 'sscnapoli',
  'AS Roma': 'ASRomaEN',
  Lazio: 'OfficialSSLazio',
  Sassuolo: 'SassuoloENG',
  Fiorentina: 'ACFFiorentinaEN',
  Atalanta: 'Atalanta_BC',
  Torino: 'TorinoFC1906_En',
  Udinese: 'Udinese_1896',
  Verona: 'HellasVeronaFC',
  Bologna: 'BolognaFC1909en',
  Cagliari: 'CagliariCalcio',
  Empoli: 'EmpoliCalcio',
  Sampdoria: 'sampdoria_en',
  Genoa: 'GenoaCFC',
  Spezia: 'acspezia_en',
  Salernitana: 'OfficialUSS1919',
  Cremonese: 'USCremonese',
  Lecce: 'OfficialUSLecce',
  Monza: 'ACMonza',
};
