export const TEAM_NAME_TO_FACEBOOK_PAGE = {
  Juventus: 'Juventus',
  Inter: 'Inter',
  'AC Milan': 'ACMilan',
  Napoli: 'SSCNapoli',
  Roma: 'officialasroma',
  Lazio: 'SSLazioOfficialPage',
  Sassuolo: 'officialsassuolocalcio',
  Fiorentina: 'ACFFiorentina',
  Atalanta: 'atalantabc',
  Torino: 'TorinoFootballClub',
  Udinese: 'UdineseCalcio1896 ',
  Cagliari: 'cagliaricalcio',
  Empoli: 'empolifcofficialpage',
  Sampdoria: 'sampdoria',
  Bologna: 'bfc1909official',
  'Hellas Verona': 'hellasveronafc',
  Genoa: 'genoaCFCofficial',
  Spezia: 'SpeziaCalcio',
  Salernitana: 'USSalernitanaOfficialPage',
  Cremonese: 'uscremonese',
  Lecce: 'USLecceOfficial',
  Monza: 'ACMonza',
};
